// Generated by CoffeeScript 1.6.3
$(function() {
  parallax.add("main", $("#main"));
  parallax.add("cv", $("#cv"));
  parallax.add("portfolio", $("#portfolio"));
  parallax.add("contacts", $("#contacts"));
  parallax.background = $("body");
  parallax.scaling = 0.4;
  parallax.main.show();
  return $(".menu-item-js").click(function(e) {
    var page;
    e.preventDefault();
    page = $(this).attr("data-page");
    switch (page) {
      case "main":
        return parallax.main.top();
      case "cv":
        return parallax.cv.left();
      case "portfolio":
        return parallax.portfolio.right();
      case "contacts":
        return parallax.contacts.bottom();
    }
  });
});
